on:
- pull_request

jobs:
  run_diff:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: git fetch
    - uses: sigmaris/action-nbdime@main
      with:
        output_dir: diffs
    - uses: actions/upload-artifact@v2
      with:
        name: diffs
        path: diffs/
