on:
- pull_request
jobs:
  run_diff:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: sigmaris/action-nbdime@v1
      with:
        output_dir: diffs
    - uses: actions/upload-artifact@v2
      with:
        name: diffs
        path: diffs/
    - uses: actions/github-script@v3
      with:
        script: |
          const response = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          })
          console.log(response)
          for(const artifact of response.data.artifacts) {
            if(artifact.name === "diffs") {
              const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
              github.issues.createComment({ issue_number, owner, repo, body: "Notebook HTML diff: " + artifact.archive_download_url });        
            }
          }
