on:
- pull_request
jobs:
  run_diff:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: sigmaris/action-nbdime@main
      with:
        output_dir: diffs
    - uses: actions/upload-artifact@v2
      with:
        name: diffs
        path: diffs/
    - uses: actions/github-script@v3
      with:
        script: |
          const response = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          })
          for(const artifact of response.data.artifacts) {
            console.log("Artifact download URL:", artifact.archive_download_url)
          }
